version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis:6379
