version: "3"

services:
  commenting-api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - cockroach
      - schema
    environment:
      - SERVICE_NAME=commenting-api
      - DATABASE_URL=postgresql://root@cockroach:26257/commenting?sslmode=disable
      - REDIS_ADDR=redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  cockroach:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257" # SQL
      - "8081:8080" # Admin UI

  schema:
    image: cockroachdb/cockroach:latest
    depends_on:
      - cockroach
    volumes:
      - ./db/sql/database.sql:/database.sql
      - ./db/sql/schema.sql:/schema.sql
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "until cockroach sql --insecure --host=cockroach -f /database.sql;
       do echo 'Waiting for CockroachDB...'; sleep 2; done &&
       cockroach sql --insecure --host=cockroach -d commenting -f /schema.sql"
