version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  stock-api-1:
    build: .
    depends_on:
      - redis
    ports:
      - "8081:8080"

  stock-api-2:
    build: .
    depends_on:
      - redis
    ports:
      - "8082:8080"

  stock-api-3:
    build: .
    depends_on:
      - redis
    ports:
      - "8083:8080"
